# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bab8949e840a44344485c5e61be6664"
name = "R8Connectprod"
handle = "r8"
application_url = "https://application-beta-lemon.vercel.app
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://application-beta-lemon.vercel.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://application-beta-lemon.vercel.app/webhooks/app/uninstalled"

   [[webhooks.subscriptions]]
   compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
   uri = "https://application-beta-lemon.vercel.app/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_shipping,write_products,write_shipping"

[auth]
redirect_urls = ["https://application-beta-lemon.vercel.app/auth/callback", "https://application-beta-lemon.vercel.app/auth/shopify/callback", "https://application-beta-lemon.vercel.app/api/auth/callback"]

[pos]
embedded = false
