# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bab8949e840a44344485c5e61be6664"
name = "R8Connectprod"
handle = "r8"
application_url = "https://tagged-cleaners-wendy-walks.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://adaptive-electrical-arbitration-ideas.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://adaptive-electrical-arbitration-ideas.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_merchant_managed_fulfillment_orders,read_orders,read_products,read_shipping,write_orders,write_products,write_shipping"

[auth]
redirect_urls = ["https://tagged-cleaners-wendy-walks.trycloudflare.com/auth/callback", "https://tagged-cleaners-wendy-walks.trycloudflare.com/auth/shopify/callback", "https://tagged-cleaners-wendy-walks.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
